on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  merge_group:
    types:
      - checks_requested
name: Test
jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9
      - name: Node
        uses: actions/setup-node@v4
        with:
          cache: "pnpm"
          node-version: 22
      - name: Dependencies
        run: pnpm install
      - name: Commitlint
        run: pnpm --silent commitlint -l
      - name: Prettier
        run: pnpm --silent pretty
      - name: ESLint
        run: pnpm --silent lint
      - name: Test
        run: pnpm test
      - name: Coverage
        uses: coverallsapp/github-action@v2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
